"""Render a ReviewResult as Markdown (for CLI output / PR summary comments)."""

from __future__ import annotations

from .models import ReviewComment, ReviewResult, Severity

_SEV_BADGE = {
    Severity.CRITICAL: "🔴 **Critical**",
    Severity.WARNING: "🟠 **Warning**",
    Severity.SUGGESTION: "🔵 **Suggestion**",
    Severity.PRAISE: "✅ **Praise**",
}
_VERDICT_LABEL = {
    "approve": "✅ APPROVE",
    "request_changes": "⛔ REQUEST CHANGES",
    "comment": "💬 COMMENT",
}


def render_comment_body(c: ReviewComment) -> str:
    """Body for a single inline comment (GitHub-flavored markdown)."""
    parts = [f"{_SEV_BADGE[c.severity]} · `{c.category}` · _{c.source}_"]
    parts.append("")
    parts.append(c.message)
    if c.suggestion:
        parts.append("")
        parts.append("**Suggested change:**")
        parts.append("```suggestion")
        parts.append(c.suggestion)
        parts.append("```")
    if c.context_refs:
        parts.append("")
        parts.append("Related: " + ", ".join(f"`{r}`" for r in c.context_refs))
    return "\n".join(parts)


def render_summary_comment(result: ReviewResult) -> str:
    """Top-level PR summary comment."""
    lines: list[str] = []
    lines.append("## 🔍 RepoLens Code Review")
    lines.append("")
    lines.append(f"**Verdict: {_VERDICT_LABEL[result.summary.verdict]}** — "
                 f"{len(result.comments)} comment(s), {result.blocking_count} blocking")
    lines.append("")
    if result.summary.overview:
        lines.append(f"> {result.summary.overview}")
        lines.append("")
    if result.summary.strengths:
        lines.append("**Strengths:**")
        for s in result.summary.strengths:
            lines.append(f"- {s}")
        lines.append("")

    by_sev: dict[Severity, list[ReviewComment]] = {}
    for c in result.comments:
        by_sev.setdefault(c.severity, []).append(c)
    for sev in (Severity.CRITICAL, Severity.WARNING, Severity.SUGGESTION, Severity.PRAISE):
        group = by_sev.get(sev, [])
        if not group:
            continue
        lines.append(f"### {_SEV_BADGE[sev].split('**')[1]}s ({len(group)})")
        for c in group:
            loc = f"`{c.path}:{c.line}`" if c.line else f"`{c.path}`"
            first_line = c.message.split("\n")[0][:160]
            lines.append(f"- {loc} — {first_line}")
        lines.append("")

    lines.append("---")
    meta = [f"files reviewed: {result.files_reviewed}"]
    if result.files_skipped:
        meta.append(f"skipped: {len(result.files_skipped)}")
    if result.context_files_used:
        meta.append(f"repo context: {len(result.context_files_used)} files")
    if result.model:
        meta.append(f"model: `{result.model}`")
    lines.append("_" + " · ".join(meta) + " — generated by [RepoLens](https://github.com/saketkumar-18/repolens)_")
    return "\n".join(lines)


def render_full_report(result: ReviewResult) -> str:
    """Full markdown report for CLI/file output."""
    lines: list[str] = []
    lines.append(f"# RepoLens Review — {result.repo}"
                 + (f" PR #{result.pr_number}" if result.pr_number else ""))
    lines.append("")
    lines.append(f"- base: `{result.base_ref}` ← head: `{result.head_ref}`"
                 + (f" @ `{result.head_sha[:10]}`" if result.head_sha else ""))
    lines.append(f"- files reviewed: {result.files_reviewed}"
                 + (f" (skipped: {', '.join(result.files_skipped)})" if result.files_skipped else ""))
    if result.context_files_used:
        lines.append(f"- repo context retrieved from: {', '.join(result.context_files_used)}")
    if result.model:
        lines.append(f"- model: {result.model} ({result.tokens_used} tokens)")
    lines.append("")
    lines.append(render_summary_comment(result))
    lines.append("")
    lines.append("## Inline comments")
    lines.append("")
    if not result.comments:
        lines.append("_No comments — clean review._")
    for c in result.comments:
        loc = f"{c.path}:{c.line}" if c.line else c.path
        lines.append(f"### {loc}")
        lines.append("")
        lines.append(render_comment_body(c))
        lines.append("")
    return "\n".join(lines)
